name: Build a WAR file using Maven and Deploy Java App to Tomcat running in AWS EC2
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Build with Maven
      run: mvn clean package -DskipTests
    - name: Deploy to Tomcat
      run: |
         WAR_FILE=$(ls mywebApp/target/*.war | head -n 1)
           echo "Deploying $WAR_FILE to Tomcat .."
          curl -v -u "${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }}" \
                        --upload-file "$WAR_FILE" \
           "http://${{ secrets.TOMCAT_HOST }}:8080/manager/text/deploy?path=/mywebApp&update=true"   
